Metrics/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 25

# For tests
Style/BlockDelimiters:
  Enabled: false

# Stupid frenchie
Style/AsciiComments:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

AllCops:
  Exclude:
    - 'bin/*'
    - 'spec/spec_helper.rb'
    - 'lib/realdebrid/version.rb'
    - 'Rakefile'
    - 'raindrops.gemspec'
    - 'db/migrate/*'
    - 'spec/dummy/**/*'
    - 'vendor/**/*'